{% set version = "1.7.0" %}

package:
  name: panoptes-client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/panoptes-client/panoptes_client-{{ version }}.tar.gz
  sha256: d9f5f402396c25125b93ffcdc05b9983a8c9e956a589236c1cd8ba8b2989f86d

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - future >=0.16
    - python >={{ python_min }}
    - python-magic >=0.4
    - redo >=1.7
    - requests >=2.4.2
    - six >=1.9

test:
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - panoptes_client
  commands:
    - pip check
    - pytest -vv --pyargs panoptes_client --cov=panoptes_client --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=72

about:
  summary: This package is the Python SDK for Panoptes, the platform behind the Zooniverse.
  home: https://github.com/zooniverse/panoptes-python-client
  license: Apache-2.0
  license_file: LICENSE
  description: |-
    This module is intended to allow programmatic management of projects,
    providing high level access to the API for common project management tasks.

extra:
  recipe-maintainers:
    - bollwyvl
