{% set version = "1.6.2" %}

package:
  name: panoptes-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panoptes-client/panoptes_client-{{ version }}.tar.gz
  sha256: d842596c5ed6d4b0a85de2ff256f63d8fc5f657927f2ec8b9be10070682c942b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - future >=0.16,<0.19
    - python >=3.7
    - python-magic >=0.4,<0.5
    - redo >=1.7
    - requests >=2.4.2,<2.29
    - six >=1.9

test:
  imports:
    - panoptes_client
  commands:
    - pip check
    - pytest -vv --pyargs panoptes_client --cov=panoptes_client --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=72
  requires:
    - pip
    - pytest-cov

about:
  summary: This package is the Python SDK for Panoptes, the platform behind the Zooniverse.
  home: https://github.com/zooniverse/panoptes-python-client
  license: Apache-2.0
  license_file: LICENSE
  description: |-
    This module is intended to allow programmatic management of projects,
    providing high level access to the API for common project management tasks.

extra:
  recipe-maintainers:
    - bollwyvl
