# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.7.0

package:
  name: panoptes-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/panoptes-client/panoptes_client-${{ version }}.tar.gz
  sha256: d9f5f402396c25125b93ffcdc05b9983a8c9e956a589236c1cd8ba8b2989f86d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - future >=0.16
    - python >=${{ python_min }}
    - python-magic >=0.4
    - redo >=1.7
    - requests >=2.4.2
    - six >=1.9

tests:
  - python:
      imports: panoptes_client
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - coverage run --source panoptes_client --branch -m pytest -vv --tb=long --color=yes --pyargs panoptes_client
      - coverage report --show-missing --skip-covered --fail-under=70

about:
  summary: This package is the Python SDK for Panoptes, the platform behind the Zooniverse.
  license: Apache-2.0
  license_file: LICENSE
  description: |-
    This module is intended to allow programmatic management of projects,
    providing high level access to the API for common project management tasks.
  homepage: https://github.com/zooniverse/panoptes-python-client

extra:
  recipe-maintainers:
    - bollwyvl
